import Link from "next/link";

const steps = [
  ["01", "Petani terverifikasi", "Dokumen dan kualitas diperiksa sebelum produk tampil."],
  ["02", "Buyer memilih", "Gabungkan ikan dari beberapa petani dalam satu pesanan."],
  ["03", "Kami konsolidasikan", "Inspeksi di titik kumpul, lot tercatat, lalu ekspor terjadwal."],
  ["04", "Tiba dan terlindungi", "Buyer punya 24 jam untuk klaim DOA dengan bukti."],
];
const faq = [
  ["Apa itu batas DOA 5%?", "DOA sampai 5% dipotong dari pembayaran petani. Di atas 5% tidak otomatis dibebankan dan dimediasi bersama buyer serta petani."],
  ["Kapan petani dibayar?", "Pembayaran 100% dilepas setelah ikan tiba di gudang buyer dan masa klaim selesai, paling lambat sesuai tenggat yang disepakati."],
  ["Apakah NusaFin eksportir?", "NusaFin memfasilitasi transaksi dan konsolidasi bersama mitra ekspor serta logistik yang sesuai."],
  ["Negara tujuan mana?", "Fokus awal Eropa dan Amerika Serikat, mengikuti CITES, Lacey Act, health certificate, GDPR, dan aturan tujuan."],
];
export default function Home() {
  return <main>
    <nav className="nav"><Link className="brand" href="#top">Nusa<span>Fin</span></Link><div className="links"><Link href="#cara">Cara kerja</Link><Link href="#tentang">Tentang</Link><Link href="#kebijakan">Kebijakan</Link><Link href="#faq">FAQ</Link></div><div className="actions"><Link href="/login">Masuk</Link><Link className="button small" href="/register">Daftar</Link></div></nav>
    <section id="top" className="hero section"><div><p className="eyebrow">DARI PERAIRAN NUSANTARA KE PASAR DUNIA</p><h1>Ekspor ikan hias,<br/><em>lebih terhubung.</em></h1><p className="lead">NusaFin menyatukan petani terverifikasi, buyer internasional, dan pengiriman terkonsolidasi dalam satu alur transparan.</p><div className="heroActions"><Link className="button" href="/register?role=farmer">Gabung sebagai petani</Link><Link className="button ghost" href="/app/catalog">Jelajahi katalog</Link></div><div className="stats"><b>24 jam<small>Jendela klaim DOA</small></b><b>5%<small>Batas DOA otomatis</small></b><b>EU + US<small>Pasar tujuan awal</small></b></div></div><div className="fishCard"><div className="glow"/><p>CURATED COLLECTION</p><div className="fish">◖<span>◉</span>≋</div><h3>Premium Betta</h3><small>Jakarta, Indonesia · Grade A</small><div className="tags"><i>Verified farmer</i><i>Export ready</i></div></div></section>
    <section id="cara" className="section pale"><p className="eyebrow">ALUR YANG JELAS</p><h2>Dari kolam hingga gudang buyer</h2><div className="grid four">{steps.map(([n,t,d])=><article className="step" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
    <section id="tentang" className="section split"><div><p className="eyebrow">TENTANG NUSAFIN</p><h2>Petani fokus merawat.<br/>Kami urus jalur ekspornya.</h2></div><div><p className="lead smaller">Banyak petani unggul dalam budidaya, tetapi akses buyer, dokumen, dan logistik ekspor masih rumit. NusaFin hadir sebagai jembatan—bukan pengganti petani.</p><ul><li>Katalog multi-petani terkurasi</li><li>Titik kumpul dan kode lot transparan</li><li>Pembayaran dan klaim terlacak</li></ul></div></section>
    <section id="kebijakan" className="section dark"><p className="eyebrow">PERLINDUNGAN TRANSAKSI</p><h2>Aturan DOA, tanpa area abu-abu.</h2><div className="grid three"><article><b>24H</b><h3>Jendela klaim</h3><p>Klaim diajukan maksimal 24 jam sejak ikan masuk gudang buyer, dengan foto/video.</p></article><article><b>≤5%</b><h3>Potongan terukur</h3><p>Kompensasi otomatis dipotong dari pembayaran petani sesuai lot terkait.</p></article><article><b>&gt;5%</b><h3>Eskalasi manusia</h3><p>Tidak ada keputusan otomatis. Buyer, petani, dan admin berkomunikasi mencari resolusi.</p></article></div><p className="legalNote">Kejadian luar biasa setelah batas waktu dapat dibicarakan manual dan tercatat dalam audit log.</p></section>
    <section id="faq" className="section"><div className="split"><div><p className="eyebrow">PERTANYAAN UMUM</p><h2>Yang perlu diketahui sebelum mulai.</h2></div><div>{faq.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section>
    <section id="legal" className="section pale"><div className="grid two"><article className="legalCard"><p className="eyebrow">TERMS</p><h2>Ketentuan Layanan</h2><p>NusaFin bertindak sebagai fasilitator marketplace dan konsolidasi. Harga, risiko FCA/FOB, klaim, pembayaran, dan tanggung jawab setiap pihak dijelaskan sebelum transaksi.</p><Link href="/terms">Baca ketentuan lengkap →</Link></article><article className="legalCard"><p className="eyebrow">PRIVACY</p><h2>Privasi & Data</h2><p>Data dikumpulkan seperlunya, dilindungi sesuai UU PDP dan GDPR, serta tidak dijual. Pengguna dapat meminta akses atau penghapusan data.</p><Link href="/privacy">Baca kebijakan lengkap →</Link></article></div></section>
    <section id="kontak" className="section cta"><p className="eyebrow">MULAI PERJALANAN</p><h2>Ikan terbaik Nusantara.<br/>Buyer di seluruh dunia.</h2><div className="heroActions"><Link className="button light" href="/register">Buat akun NusaFin</Link><a className="button ghostLight" href="mailto:hello@nusafin.example">Hubungi kami</a></div></section>
    <footer><Link className="brand" href="#top">Nusa<span>Fin</span></Link><p>Marketplace ekspor ikan hias Indonesia.</p><div><Link href="/terms">Ketentuan</Link><Link href="/privacy">Privasi</Link><a href="mailto:hello@nusafin.example">Kontak</a></div><small>© 2026 NusaFin. Prototype untuk review.</small></footer>
  </main>
}